# -*- coding: utf-8 -*-
"""Copy of Econometrics Empirical Exercises 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12M-2PsGGCrWwd9Pl9vr0Or51-gamsdSV

#ECON-UB 251 Assignment 1 | Fall 2025 | Haroon Malik

##Theory

### 1. Derive the OLS Estimator of $\beta_1$ in the model $Y_i=\beta_1X_i+u_i$.

---



First, define the residual sum of squares to be:

$RSS = \sum_{i=1}^n (Y_i-(u_i+\hat\beta_1X_i))^2$.

We will minimize the residual sum of squares to derive the OLS estimator. Take the partial derivative with respect to $u_i$, and then $\hat\beta_1$, setting them equal to zero:

$\frac{\partial RSS}{\partial u_i} = -2\sum_{i=1}^n (Y_i-u_i-\hat\beta_1X_i) = -2[\sum_{i=1}^n(Y_i)-nu_i-\hat\beta_1\sum_{i=1}^n(X_i)] = -2[-n\bar Y + nu_i + n\hat\beta_1\bar X] = 0$

$\frac{\partial RSS}{\partial\hat\beta_1} = -2\sum_{i=1}^n(Y_i-nu_i-\hat\beta_1X_i)X_i = -2[\sum_{i=1}^n(X_iY_i) - nu_i\bar X-\hat\beta_1\sum_{i=1}^n(X_i^2) = 0$

From $\frac{\partial RSS}{\partial u_i}$, we get:

$-2[-n\bar Y + nu_i + n\hat\beta_1\bar X] = 0 \iff -\bar Y + u_i + \hat\beta_1 \bar X = 0 \iff u_i = \bar Y - \hat\beta_1 \bar X$.

We substitute this into the $\frac{\partial RSS}{\partial\hat\beta_1}$ equation accordingly:

$-2[\sum_{i=1}^n(X_iY_i) - nu_i\bar X-\hat\beta_1\sum_{i=1}^n(X_i^2) = 0 \iff \frac{1}{n}\sum_{i=1}^nX_iY_i - \bar X u_i - \frac{1}{n} \hat\beta_1 \sum_{i=1}^n X_i^2 = 0 \iff $

$\frac{1}{n}\sum_{i=1}^nX_iY_i - \bar X (\bar Y - \hat\beta_1 \bar X) - \frac{1}{n} \hat\beta_1 \sum_{i=1}^n X_i^2 = 0 \iff \frac{1}{n}\sum_{i=1}^nX_iY_i - \bar X \bar Y + \hat\beta_1 \bar X^2 - \frac{1}{n} \hat\beta_1 \sum_{i=1}^n X_i^2 = 0 \iff \hat\beta_1(\frac{1}{n} \sum_{i=1}^n X_i^2 - \bar X^2) = \frac{1}{n} \sum_{i=1}^n X_i Y_i - \bar X \bar Y.$

We divide the product to isolate $\hat\beta_1$ and get:

$\hat\beta_1 = \frac{\frac{1}{n} \sum_{i=1}^n X_i Y_i - \bar X \bar Y}{\frac{1}{n} \sum_{i=1}^n X_i^2 - \bar X^2} = \frac{\sum_{i=1}^n (X_i-\bar X)(Y_i-\bar Y)}{\sum_{i=1}^n (X_i - \bar X)^2}$. $\square$

### 2. Does the sample average have a normal distribution (in large samples) even when the observations are not normally distributed? Does the CLT really hold?
"""

import numpy as np
import matplotlib.pyplot as plt

#define variables
K = 4
N=1000
B=1000
i=1
data=[]

#iterate the simulation of the t distr. B times, recording each trial's mean in the list data
while i <= B:
  t=0
  t = np.mean(np.random.standard_t(K, N))/B
  data.append(t)
  i+=1

#red histogram of normal distr.
plt.hist(np.random.normal(loc=0, scale=.0001, size=1000), alpha=0.3, bins=20, color='r')
#blue histogram of simulation data
plt.hist(data, bins=20, alpha=0.7, color='b')

"""As observed from the histogram of the sample average, the distribution follows a very similar pattern to the normal distribution and deviates as expected due to its low degrees of freedom, which we have defined to be 4. The distribution has a lower peak in the middle than the typical normal distribution, indicating that the values may be more spread out relative to the scale of the simulation. The CLT holds because for the large N that we have used here, the distribution approaches a normal one.

##Empirical

### 3.
"""

import pandas as pd

#read in file
var_names = ["Credit_Score","First_Payment_date","First_Time_Homebuyer", "Maturity_Date",
"MSA","Mortgage_Insurance_Percentage","Number_Units","Occupancy_Status","CLTV",
"DTI","UPB","LTV","Interest_Rate","Channel","Prepayment_Penalty",
"Amortization_Type","State","Property_Type","Postal_Code","Sequence_Number",
"Purpose","Loan_Term","Number_Borrowers","Seller_Name","Servicer_Name",
"Super_Conforming","Pre-HARP_Loan","Program_Indicator","HARP_Indicator",
"Valuation_Method","Interest_Only", "Insurance_cancellation"]
loans = pd.read_table("/content/sample_orig_2015.txt",
delimiter = "|", names = var_names)

#preview the data
loans.head()

#remove rows with NaN values
loans['Interest_Rate'] = loans['Interest_Rate'].dropna()

#remove rows with other missing values
loans=loans.drop(loans[loans['Credit_Score'] == 9999].index)
loans=loans.drop(loans[loans['First_Time_Homebuyer'] == 9].index)
loans=loans.drop(loans[loans['MSA'] == 'Null'].index)
loans=loans.drop(loans[loans['Mortgage_Insurance_Percentage'] == 999].index)
loans=loans.drop(loans[loans['Number_Units'] == 99].index)
loans=loans.drop(loans[loans['Occupancy_Status'] == 9].index)
loans=loans.drop(loans[loans['CLTV'] == 999].index)
loans=loans.drop(loans[loans['DTI'] == 999].index)
loans=loans.drop(loans[loans['LTV'] == 999].index)
loans=loans.drop(loans[loans['Channel'] == 9].index)
loans=loans.drop(loans[loans['Property_Type'] == 99].index)
loans=loans.drop(loans[loans['Postal_Code'] == 00].index)
loans=loans.drop(loans[loans['Purpose'] == 9].index)
loans=loans.drop(loans[loans['Number_Borrowers'] == 99].index)

#summary stats
print(loans['Interest_Rate'].describe())
print(loans['Interest_Rate'].skew())
print(loans['Interest_Rate'].kurt())
print(loans['Credit_Score'].describe())
print(loans['Credit_Score'].skew())
print(loans['Credit_Score'].kurt())
print(loans['DTI'].describe())
print(loans['DTI'].skew())
print(loans['DTI'].kurt())
print(loans['LTV'].describe())
print(loans['LTV'].skew())
print(loans['LTV'].kurt())

"""The distribution for Interest_Rate is skewed slightly left, with a mean of 3.96%. It is slightly flatter than the normal distribution. The average credit score is roughly 752, and is skewed leftward (i.e. more borrowers have higher credit scores) and flatter than the normal distribution. The average DTI, or Debt-to-Income ratio, is roughly 33.84 with a relatively high standard deviation of 9.39. The distribution is skewed slightly leftward and is flatter than the normal distribution. The Loan-to-Value's mean is 73.64 with a relatively high standard deviation of 16.46, and is skewed heavily to the left (i.e. more loans have a high LTV).

### 4.
"""

import matplotlib.pyplot as plt

#histogram of IR
plt.hist(loans['Interest_Rate'], bins=10)
plt.xlabel('Interest Rate')
plt.ylabel('Frequency')
plt.title('Interest Rates')
plt.show()

#histogram of credit score
plt.hist(loans['Credit_Score'], bins=10)
plt.xlabel('Credit Score')
plt.ylabel('Frequency')
plt.title('Credit Scores')
plt.show()

#histogram of LTV
plt.hist(loans['LTV'], bins=10)
plt.xlabel('Loan-to-Value')
plt.ylabel('Frequency')
plt.title('Loan-to-Value')
plt.show()

"""Out of these three variables, Interest_Rate is the only one that appears to resemble a normal distribution relatively closely. The majority of the values fall close to the middle of the range around roughly 4%, with a very slight skew left. Credit_Score and LTV are skewed heavily to the left as expected from the summary statistics computed previously, meaning that the majority of their values are concentrated towards the higher end of the distribution.

It would make sense for Credit_Score and LTV to affect the Interest_Rate value of a loan, since both variables are key factors that banks may use in assessing the risk of lending to a borrower. Generally, borrowers with a higher credit score are perceived as less likely to default on a loan and expected to make payments on time. LTV serves as another risk factor; the greater the LTV, the more of an asset's value that the borrower is borrowing. This means that a default may be slightly more likely and that in the event of one, it will be difficult for the bank to recoup its losses. Interest rates are typically higher for loans that pose more risk to the lender; for example, private student loan rates for college students without a cosigner are typically higher than those for financially stable adults with high credit scores purchasing a home, because the bank has a much greater chance of the borrower defaulting in the first case. Thus, it seems likely that these factors may influence banks' decision-making regarding lending and that there would be a negative correlation between IR and credit score and a positive correlation between IR and LTV. That is, higher credit scores would pay lower interest rates overall and higher LTVs would pay higher interest rates overall.

### 5.
"""

#IR and CS
print(loans['Interest_Rate'].corr(loans['Credit_Score']))
#IR and DTI
print(loans['Interest_Rate'].corr(loans['DTI']))
#IR and LTV
print(loans['Interest_Rate'].corr(loans['LTV']))

"""As expected, it was found that the correlation between the interest rate and credit score is negative; it makes sense that for borrowers with higher credit scores (i.e. more trustworthy), banks will offer lower interest rates. Additionally, there is a positive correlation between the interest rate and LTV of a similar magnitude, which is understandable since a higher LTV indicates more risk of defaulting. The correlation for DTI (Debt-to-Income ratio) is also positive, which makes sense when thought about conceptually. If an individual takes on more debt with respect to their income than another individual, banks may see them as a riskier borrower due to their tendency to hold debt, and thus may charge a higher interest rate.

### 6.
"""

#create new column 'type' and categorize loans as prime/subprime
loans['type'] = 'prime'
loans.loc[loans['Credit_Score'] < 670, 'type'] = 'subprime'

#compute means of interest rates
print(np.mean(loans.loc[loans['type'] == 'prime', 'Interest_Rate']))
print(np.mean(loans.loc[loans['type'] == 'subprime', 'Interest_Rate']))

"""The average interest rate for loans categorized as 'prime' is roughly 0.30% less than the average interest rate for loans categorized as 'subprime,' however we need to conduct hypothesis testing in order to determine whether or not this difference is significant.

### 7.
"""

from scipy import stats

prime_interest_rates = loans.loc[loans['type'] == 'prime', 'Interest_Rate']
subprime_interest_rates = loans.loc[loans['type'] == 'subprime', 'Interest_Rate']

# t-test
ttest_result = stats.ttest_ind(prime_interest_rates, subprime_interest_rates, equal_var=False)

print("T-Statistic: " + str(ttest_result))

"""The critical value for a two-sided t-test with 5% significance is |1.96|; since t=-27.88 < -1.96, we reject the null hypothesis and conclude that the two expected interest rates are different.

### 8.

The p-value derived from testing the two variables is considerably lower than $\alpha = 0.01$; thus we can conclude that the expected value is significantly greater for prime mortgages, rejecting the 1-sided null hypothesis.

### 9.
"""

from statsmodels.formula.api import ols

model_IRs = ols('Interest_Rate ~ Credit_Score', data=loans).fit()
print(model_IRs.params)

"""These coefficients come from a least squares regression with interest rate as the variable being predicted and credit score as the explanatory variable. The interpretation at x = 0 that a borrower with a credit score of 0 would end up with a 5.97% interest rate is nonsensical, but the coefficient of -0.002676 means that the model predicts that as credit score increases by 1, the expected interest rate for a loan decreases by 0.002676.

### 10.
"""

t_cs = model_IRs.tvalues['Credit_Score']
p_cs = model_IRs.pvalues['Credit_Score']

print("T-Stat:" + str(t_cs))

"""For a two-sided t-test at significance level 1%, the critical value would be roughly |3.291|. The computed T-Stat of -58.87 is significantly lower than -3.291, and thus, we can reject the null hypothesis and conclude that the credit score of a borrower does in fact have a significant statistical relationship with the interest rate of a loan. This means that we find it to be a relevant variable in determining what the interest rate of a loan may be."""